### ISSUE TITLE
Allow users to resize columns

### ISSUE THREAD

**Issue by alexsb** [Caleydo/taggle#347] opened 2017-04-25 00:10 UTC
Here, a couple of long country names waste a lot of space. 

![image](https://cloud.githubusercontent.com/assets/2039375/25363622/30fb97a2-2919-11e7-99cc-5ad927d30de3.png)

We want to be able to dynamically resize columns.

**Comment by mstreit** [comment] 2017-04-25 06:33
duplicate of #106.

**Closed by mstreit** 2017-04-25 06:33 UTC
Labels: Usability
