### ISSUE TITLE
Adding a list to an empty taggle results in wrong block size / squishing

### ISSUE THREAD

**Issue by alexsb** [Caleydo/taggle#343] opened 2017-04-24 23:25 UTC
![image](https://cloud.githubusercontent.com/assets/2039375/25362725/f56d69be-2912-11e7-9976-7881fbcfd3a6.png)

Here, I've just added AIDS_Countries, nothing else. When I click on that column it resolves.

**Comment by mstreit** [comment] 2017-04-25 06:30
Yes, that's because the aggregated vis for string columns is not implemented yet. 
Related to #311.

**Comment by mstreit** [comment] 2017-05-02 08:00
Duplicate of #311.

**Closed by mstreit** 2017-05-02 08:00 UTC
Labels: bug
