### ISSUE TITLE
Encode missing values in heatmaps

### ISSUE THREAD

**Issue by mstreit** [Caleydo/taggle#316] opened 2017-03-28 18:03 UTC

**Comment by mijar** [comment] 2017-03-29 14:18
The problem is related not only to the heatmaps, but also to numerical columns - right now I see no difference between the lowest value and null...in the following case it is related to the HIC prevention column, where quite a lot of values are null. But most probably, in developed countries in Europe there is quite good knowledge of the prevention...
This difference needs to be covered in my opinion, too

![image](https://cloud.githubusercontent.com/assets/7511570/24459194/3c81b620-149b-11e7-9096-446f9e14a692.png)

**Comment by mstreit** [comment] 2017-03-29 16:03
Yes, I agree. This needs to be solved in all heatmap based visualizations.

**Comment by mstreit** [comment] 2017-05-30 11:04
The missing value encoding in the heatmap was fixed in https://github.com/phovea/phovea_vis/issues/57.
However, we need to systematically handle this in all other column visualizations as well (bars, strings, etc.).

**Comment by thinkh** [comment] 2017-05-31 15:31
Opened a new issue for missing encodings in other columns. 
--> Close this one.

**Closed by thinkh** 2017-05-31 15:31 UTC
Labels: enhancement
